// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_apod/test/widget/calendar_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter_apod/interface/i_apod_json_get.dart' as _i2;
import 'package:flutter_apod/interface/i_database_sql.dart' as _i3;
import 'package:flutter_apod/interface/i_picture_saver.dart' as _i4;
import 'package:flutter_apod/model/apod_api_data.dart' as _i10;
import 'package:flutter_apod/model/apod_db_data.dart' as _i5;
import 'package:flutter_apod/provider/apod_calendar_provider.dart' as _i6;
import 'package:flutter_apod/provider/apod_data_provider.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIApodApiDataGet_0 extends _i1.SmartFake
    implements _i2.IApodApiDataGet {
  _FakeIApodApiDataGet_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIApodDbSqlCmd_1 extends _i1.SmartFake implements _i3.IApodDbSqlCmd {
  _FakeIApodDbSqlCmd_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIPictureSaver_2 extends _i1.SmartFake implements _i4.IPictureSaver {
  _FakeIPictureSaver_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApodDbData_3 extends _i1.SmartFake implements _i5.ApodDbData {
  _FakeApodDbData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApodCalendarProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodCalendarProvider extends _i1.Mock
    implements _i6.ApodCalendarProvider {
  @override
  set showDialogFunc(
          _i7.Future<void> Function(
            String,
            String,
          )? _showDialogFunc) =>
      super.noSuchMethod(
        Invocation.setter(
          #showDialogFunc,
          _showDialogFunc,
        ),
        returnValueForMissingStub: null,
      );
  @override
  double get progressValue => (super.noSuchMethod(
        Invocation.getter(#progressValue),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);
  @override
  bool get monthDataDownLoadLocker => (super.noSuchMethod(
        Invocation.getter(#monthDataDownLoadLocker),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  Map<String, _i5.ApodDbData> get apodDataMap => (super.noSuchMethod(
        Invocation.getter(#apodDataMap),
        returnValue: <String, _i5.ApodDbData>{},
        returnValueForMissingStub: <String, _i5.ApodDbData>{},
      ) as Map<String, _i5.ApodDbData>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool goGetMonthData(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #goGetMonthData,
          [
            year,
            month,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  List<String> checkApiDate(List<String>? apiDays) => (super.noSuchMethod(
        Invocation.method(
          #checkApiDate,
          [apiDays],
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);
  @override
  void addEventData(List<_i5.ApodDbData>? datas) => super.noSuchMethod(
        Invocation.method(
          #addEventData,
          [datas],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApodDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodDataProvider extends _i1.Mock implements _i9.ApodDataProvider {
  @override
  _i2.IApodApiDataGet get apodApiDataGetter => (super.noSuchMethod(
        Invocation.getter(#apodApiDataGetter),
        returnValue: _FakeIApodApiDataGet_0(
          this,
          Invocation.getter(#apodApiDataGetter),
        ),
        returnValueForMissingStub: _FakeIApodApiDataGet_0(
          this,
          Invocation.getter(#apodApiDataGetter),
        ),
      ) as _i2.IApodApiDataGet);
  @override
  _i3.IApodDbSqlCmd get apodDbSqlCmd => (super.noSuchMethod(
        Invocation.getter(#apodDbSqlCmd),
        returnValue: _FakeIApodDbSqlCmd_1(
          this,
          Invocation.getter(#apodDbSqlCmd),
        ),
        returnValueForMissingStub: _FakeIApodDbSqlCmd_1(
          this,
          Invocation.getter(#apodDbSqlCmd),
        ),
      ) as _i3.IApodDbSqlCmd);
  @override
  _i4.IPictureSaver get pictureSaver => (super.noSuchMethod(
        Invocation.getter(#pictureSaver),
        returnValue: _FakeIPictureSaver_2(
          this,
          Invocation.getter(#pictureSaver),
        ),
        returnValueForMissingStub: _FakeIPictureSaver_2(
          this,
          Invocation.getter(#pictureSaver),
        ),
      ) as _i4.IPictureSaver);
  @override
  _i5.ApodDbData get apodDbData => (super.noSuchMethod(
        Invocation.getter(#apodDbData),
        returnValue: _FakeApodDbData_3(
          this,
          Invocation.getter(#apodDbData),
        ),
        returnValueForMissingStub: _FakeApodDbData_3(
          this,
          Invocation.getter(#apodDbData),
        ),
      ) as _i5.ApodDbData);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i7.Future<void> openDatabase() => (super.noSuchMethod(
        Invocation.method(
          #openDatabase,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> closeDatabase() => (super.noSuchMethod(
        Invocation.method(
          #closeDatabase,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getTodayData() => (super.noSuchMethod(
        Invocation.method(
          #getTodayData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<_i5.ApodDbData> saveApiData(_i10.ApodApiData? apiData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApiData,
          [apiData],
        ),
        returnValue: _i7.Future<_i5.ApodDbData>.value(_FakeApodDbData_3(
          this,
          Invocation.method(
            #saveApiData,
            [apiData],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.ApodDbData>.value(_FakeApodDbData_3(
          this,
          Invocation.method(
            #saveApiData,
            [apiData],
          ),
        )),
      ) as _i7.Future<_i5.ApodDbData>);
  @override
  _i7.Future<List<_i5.ApodDbData>> getMonthDataByDataBase(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthDataByDataBase,
          [
            year,
            month,
          ],
        ),
        returnValue: _i7.Future<List<_i5.ApodDbData>>.value(<_i5.ApodDbData>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.ApodDbData>>.value(<_i5.ApodDbData>[]),
      ) as _i7.Future<List<_i5.ApodDbData>>);
  @override
  _i7.Future<List<_i5.ApodDbData>> getAllData() => (super.noSuchMethod(
        Invocation.method(
          #getAllData,
          [],
        ),
        returnValue: _i7.Future<List<_i5.ApodDbData>>.value(<_i5.ApodDbData>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.ApodDbData>>.value(<_i5.ApodDbData>[]),
      ) as _i7.Future<List<_i5.ApodDbData>>);
  @override
  _i7.Future<List<_i5.ApodDbData>> getFavorite() => (super.noSuchMethod(
        Invocation.method(
          #getFavorite,
          [],
        ),
        returnValue: _i7.Future<List<_i5.ApodDbData>>.value(<_i5.ApodDbData>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i5.ApodDbData>>.value(<_i5.ApodDbData>[]),
      ) as _i7.Future<List<_i5.ApodDbData>>);
  @override
  _i7.Future<void> changeFavorite(_i5.ApodDbData? data) => (super.noSuchMethod(
        Invocation.method(
          #changeFavorite,
          [data],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
